config/routes.rb
PushRails::Application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'sign-in', to: 'devise/sessions#new', as: :new_session
    get 'sign-out', to: 'devise/sessions#destroy', as: :destroy_session
  end

  resources :receivers, only: [:index, :show, :edit, :update]
  resources :notifications, only: [:index, :create]
  resources :services

  namespace :api do
    namespace :v1 do
      resources :receivers, only: :create
      resources :acknowledgements, only: :create
      resources :notifications, only: :create
    end
  end

  require 'sidekiq/web'
  authenticate :user, -> (u) { u.admin? } do
    mount Sidekiq::Web => '/jobs'
  end

  post '/facebook', to: 'facebook#create', as: :create_facebook
  get '/facebook/show', to: 'facebook#show', as: :show_facebook

  resources :welcome, only: [:index]
  get '/docs', to: 'welcome#docs', as: :docs
  root to: 'welcome#index'
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :user

  before_create :ensure_token_presence

  validates :name, :user, presence: true

  def to_s
    name
  end

  private

    def ensure_token_presence
      self.token = generate_token if token.blank?
    end

    def generate_token
      loop do
        token = Devise.friendly_token
        break token unless Service.where(token: token).exists?
      end
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  load_and_authorize_resource
  skip_load_resource only: :create

  def index; end
  def show; end
  def edit; end

  def update
    if @service.update_attributes(service_params)
      redirect_to services_path
    else
      render :edit
    end
  end

  def new
    @service = current_user.services.build
  end

  def create
    @service = Service.new(service_params)
    @service.user = current_user

    if @service.save
      redirect_to services_path
    else
      render :new
    end
  end

  def destroy
    @service.delete

    redirect_to services_path
  end

  private

  def service_params
    params.require(:service).permit(:name)
  end
end

app/views/services/_form.haml
= form_for @service do |f|
  .row
    .large-8.columns
      -if @service.errors.any?
        .row
          .large-12.columns
            %h3= t('service.invalid')
            = t('correct_these_fields')
            %ul.disc
              - @service.errors.full_messages.each do |msg|
                %li= msg
      .row
        .large-4.columns
          = f.label :name
          = f.text_field :name

    .large-4.columns
      = f.submit t('save'), class: 'button'
      = link_to t('cancel'), services_path

app/views/services/_service.haml
%tr
  %td= link_to service, edit_service_path(service)
  %td= service.token
  %td= time_ago_in_words service.created_at

app/views/services/edit.html.haml
= content_for :title do
  %h1 Edit #{@service}

= render 'form'

.row
  .12.columns
    %br
    %br
    %br
    = link_to t(:delete),
              service_path(@service),
              confirm: t(:confirm_delete, scope: [:service]),
              method: :delete

app/views/services/index.html.haml
= content_for :title do
  %h1 Services

.row
  .small-8.columns
    %table
      %thead
        %th= Service.human_attribute_name :name
        %th= Service.human_attribute_name :token
        %th= Service.human_attribute_name :created_at
      %tbody
        = render @services

  .small-4.columns
    = link_to t(:new, scope: [:service]),
              new_service_path,
              class: :button
    %br
    - if current_user.facebook_uid.present?
      = link_to t(:fetch, scope: [:facebook]),
                create_facebook_path,
                method: 'POST',
                class: :button
    - else
      = link_to t(:connect, scope: [:facebook]),
                user_omniauth_authorize_path(:facebook),
                class: :button

app/views/services/new.html.haml
= content_for :title do
  %h1 New Service

= render 'form'