config/routes.rb
PushRails::Application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'sign-in', to: 'devise/sessions#new', as: :new_session
    get 'sign-out', to: 'devise/sessions#destroy', as: :destroy_session
  end

  resources :receivers, only: [:index, :show, :edit, :update]
  resources :notifications, only: [:index, :create]
  resources :services

  namespace :api do
    namespace :v1 do
      resources :receivers, only: :create
      resources :acknowledgements, only: :create
      resources :notifications, only: :create
    end
  end

  require 'sidekiq/web'
  authenticate :user, -> (u) { u.admin? } do
    mount Sidekiq::Web => '/jobs'
  end

  post '/facebook', to: 'facebook#create', as: :create_facebook
  get '/facebook/show', to: 'facebook#show', as: :show_facebook

  resources :welcome, only: [:index]
  get '/docs', to: 'welcome#docs', as: :docs
  root to: 'welcome#index'
end

app/models/receiver.rb
class Receiver < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :notifications

  before_save :ensure_auth_token

  def to_s
    nickname || uid
  end

  private

    def ensure_auth_token
      self.auth_token = generate_auth_token if auth_token.blank?
    end

    def generate_auth_token
      loop do
        token = Devise.friendly_token
        break token unless Receiver.where(auth_token: token).first
      end
    end
end

app/controllers/api/v1/receivers_controller.rb
class Api::V1::ReceiversController < ActionController::Base
  before_filter :verify_params
  before_filter :verify_jwt

  def create
    @user = User.find_or_create_by_email(@user_email)

    @receiver = FetchOrBuildReceiver.call(params['uid'],
                                          params['gcm_id'],
                                          @user)
    WelcomeToPushSomething.call(@user, @receiver)
  end

  private

    def verify_jwt
      jwt = JWT.decode(params['jwt'], ENV['GOOGLE_SECRET'], false)

      if jwt['iss'] != 'accounts.google.com' &&
         jwt['aud'] != ENV['GOOGLE_ID']
        render 'auth_error', status: :unauthorized
      end

      @user_email = jwt['email']
    end

    def verify_params
      unless params['jwt'] && params['uid'] && params['gcm_id']
        render status: :bad_request, json: {}
      end
    end
end

app/controllers/receivers_controller.rb
class ReceiversController < ApplicationController
  load_and_authorize_resource

  def index
  end

  def show
  end

  def edit
  end

  def update
    if @receiver.update_attributes(receiver_params)
      flash[:success] = t('receiver.update.success', name: @receiver)
      redirect_to @receiver
    else
      render :edit
    end
  end

  private

  def receiver_params
    params.require(:receiver).permit(:nickname)
  end
end

app/views/receivers/_form.haml
= form_for @receiver do |f|
  .row
    .8.columns
      -if @receiver.errors.any?
        .row
          .12.columns
            %h3= t('receiver.invalid')
            = t('correct_these_fields')
            %ul.disc
              - @receiver.errors.full_messages.each do |msg|
                %li= msg
      .row
        .large-3.columns
          = f.label :nickname
          = f.text_field :nickname

    .4.columns
      = f.submit t('save'), class: 'button'
      = link_to t('cancel'), @receiver

app/views/receivers/_receiver.haml
%tr
  %td= link_to receiver, receiver
  %td= receiver.uid
  %td= yes_no receiver.gcm_id.present?
  %td= time_ago_in_words receiver.updated_at
  %td= time_ago_in_words receiver.created_at

app/views/receivers/edit.html.haml
= content_for :title do
  %h1 Edit #{@receiver}

.row
  .twelve.columns
    = render 'form'

app/views/receivers/index.haml
= content_for :title do
  %h1 Receivers

.row
  .small-8.columns
    %table
      %thead
        %th= Receiver.human_attribute_name :nickname
        %th= Receiver.human_attribute_name :uid
        %th= Receiver.human_attribute_name :gcm_id
        %th= Receiver.human_attribute_name :updated_at
        %th= Receiver.human_attribute_name :created_at
      %tbody
        = render @receivers

  .small-4.columns
    = link_to t('test_notification.send_button'),
              '#',
              class: 'button',
              'data-reveal-id' => 'new_notification_modal'

= content_for :modals do
  #new_notification_modal.reveal-modal.small{' data-reveal' => '' }
    %h2 Send a test notification
    .form-content
      =render 'notifications/form'
    %a.close-reveal-modal &#215;

app/views/receivers/show.html.haml
= content_for :title do
  %h1= @receiver

.row
  .twelve.columns
    = link_to t('receiver.back_to_index').html_safe,
      receivers_path

.row
  .nine.columns
    %dl
      %dt= Receiver.human_attribute_name :nickname
      %dd= @receiver.nickname

      %dt= Receiver.human_attribute_name :uid
      %dd= @receiver.uid

      %dt= Receiver.human_attribute_name :gcm_id
      %dd= @receiver.gcm_id

  .three.columns
    = link_to t('edit'), edit_receiver_path(@receiver), class: 'button'