config/routes.rb
PushRails::Application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'sign-in', to: 'devise/sessions#new', as: :new_session
    get 'sign-out', to: 'devise/sessions#destroy', as: :destroy_session
  end

  resources :receivers, only: [:index, :show, :edit, :update]
  resources :notifications, only: [:index, :create]
  resources :services

  namespace :api do
    namespace :v1 do
      resources :receivers, only: :create
      resources :acknowledgements, only: :create
      resources :notifications, only: :create
    end
  end

  require 'sidekiq/web'
  authenticate :user, -> (u) { u.admin? } do
    mount Sidekiq::Web => '/jobs'
  end

  post '/facebook', to: 'facebook#create', as: :create_facebook
  get '/facebook/show', to: 'facebook#show', as: :show_facebook

  resources :welcome, only: [:index]
  get '/docs', to: 'welcome#docs', as: :docs
  root to: 'welcome#index'
end

app/views/shared/_analytics.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45356349-1', 'pushsomething.com');
  ga('send', 'pageview');

app/views/shared/_footer.haml
%footer
  .row
    .small-12.columns
      = t :copyright, scope: [:footer]
      ©
      = Time.now.year
      Chris Marshall

app/views/shared/_top_bar.haml
.contain-to-grid
  %nav.top-bar{ 'data-topbar' => '' }
    %ul.title-area
      %li.name
        %h1= link_to 'PushSomething', root_path
    %section.top-bar-section
      %ul.right
        %li= link_to t(:docs, scope: [:topbar]), docs_path
        %li.divider
        - if signed_in?
          %li= link_to t(:signout, scope: [:topbar]), destroy_session_path
        - else
          %li= link_to t(:signin, scope: [:topbar]),
            user_omniauth_authorize_path(:google_oauth2)
    - if signed_in?
      %section.top-bar-section
        %ul.left
          %li= link_to t(:receivers, scope: [:topbar]), receivers_path
          %li= link_to t(:notifications, scope: [:topbar]), notifications_path
          %li= link_to t(:services, scope: [:topbar]), services_path